In [1]:
import sys
sys.path.append('..')
import processing
import pretty_midi


In [5]:
# loader = processing.DatasetLoader('..\\..\\dataset\\np_dataset')
# train_data, test_data = loader.get_dataloaders()
# for src, tgt, meta in train_data:
#     break
decode = processing.decode(src[0])
processing.note_to_midi(decode, "src.mid")

ZeroDivisionError: float division by zero

In [3]:
src[0].shape

torch.Size([2048])

In [3]:
src.shape

torch.Size([8, 2048])

In [3]:
import sys
sys.path.append('..')
import processing
import pretty_midi
# mid = pretty_midi.PrettyMIDI(midi_file="F:\\GitHub\\dataset\\midi_dataset\\ABBA\\Mamma_Mia.mid")
midi_notes = processing.extract_midi("F:\\GitHub\\dataset\\midi_dataset\\ABBA\\Money,_Money,_Money.mid")
encoded_notes = processing.encode(midi_notes)
decoded_notes = processing.decode(encoded_notes)
processing.note_to_midi(decoded_notes, "money.mid")

In [3]:
mid = pretty_midi.PrettyMIDI(midi_file="F:\\GitHub\\dataset\\midi_dataset\\ABBA\\Money,_Money,_Money.mid")
all_notes = []
print(mid.instruments)
# [[all_notes.append(note) for note in inst.notes] for inst in mid.instruments]
# all_notes

[Instrument(program=0, is_drum=False, name="MoneyMone"), Instrument(program=12, is_drum=False, name="MoneyMone"), Instrument(program=33, is_drum=False, name="MoneyMone"), Instrument(program=0, is_drum=True, name="MoneyMone"), Instrument(program=10, is_drum=False, name="MoneyMone"), Instrument(program=62, is_drum=False, name="MoneyMone"), Instrument(program=27, is_drum=False, name="MoneyMone"), Instrument(program=48, is_drum=False, name="MoneyMone")]


In [15]:
import random
import configs.common as cc
print(src[0][:30])
time_r_ints = 100
time_lb = cc.start_idx['time']
time_ub = cc.start_idx['time'] + cc.config.discretization.time - 1
sequence = processing.multiply_sequence(src[0], time_r_ints, time_lb, time_ub)
print(sequence[:30])

tensor([251, 265, 618, 833,  58, 224, 261, 381, 490, 833,  43, 241, 263, 357,
        618, 833,  58, 256, 305, 381, 457, 833,  43, 254, 267, 357, 618, 833,
         39, 251], device='cuda:0')
tensor([251, 265, 618, 833,  58, 224, 261, 455, 490, 833,  43, 241, 263, 357,
        618, 833,  58, 256, 305, 455, 457, 833,  43, 254, 267, 357, 618, 833,
         39, 251], device='cuda:0')


In [16]:
cc.start_idx

{'pitch': 1,
 'dyn': 129,
 'length': 257,
 'time': 357,
 'channel': 457,
 'tempo': 713}

In [8]:
src[0][:30]

tensor([248, 277, 618, 833,  63, 196, 281, 357, 519, 833,  75, 245, 261, 457,
        833,  65, 249, 261, 457, 833,  41, 245, 355, 457, 833,  43, 239, 277,
        618, 833], device='cuda:0')