In [5]:
import sys
sys.path.append('..')
import processing

loader = processing.DatasetLoader('..\\..\\dataset\\np_dataset')
train_dataloader, test_dataloader = loader.get_dataloaders()
# random_sample = loader.get_random_sample('train')
# random_sample
for src, trg, meta in train_dataloader:
    break
# src, trg, meta = random_sample

In [22]:
from train import new_model
import torch
type = 'xlstm'
model_name = 'loss_0.06_time_2025-04-16-16-38-11.pth'
model = new_model(type)
model.load_state_dict(torch.load(f'../pretrained/{type}/{model_name}'))
model.to('cuda')

C:\Users\Draco\AppData\Local\Temp\ipykernel_11840\1102517487.py:6: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f'../pretrained/{type}/{mod

xLSTM(
  (token_embedding_table): Embedding(835, 64)
  (metadata_embedding_table): Embedding(154, 64)
  (layers): ModuleList(
    (0): sLSTMblock(
      (ln): LayerNorm((64,), eps=1e-05, elementwise_affine=True)
      (conv): CausalConv1D(
        (conv): Conv1d(64, 64, kernel_size=(8,), stride=(1,), padding=(7,))
      )
      (drop): Dropout(p=0.01, inplace=False)
      (i_gate): BlockDiagonal(
        (blocks): ModuleList(
          (0-3): 4 x Linear(in_features=64, out_features=16, bias=True)
        )
      )
      (f_gate): BlockDiagonal(
        (blocks): ModuleList(
          (0-3): 4 x Linear(in_features=64, out_features=16, bias=True)
        )
      )
      (o_gate): BlockDiagonal(
        (blocks): ModuleList(
          (0-3): 4 x Linear(in_features=64, out_features=16, bias=True)
        )
      )
      (z_gate): BlockDiagonal(
        (blocks): ModuleList(
          (0-3): 4 x Linear(in_features=64, out_features=16, bias=True)
        )
      )
      (ri_gate): BlockDiago

In [28]:
output = model(src, meta)
print(src[0])
print(output[0].argmax(-1))

tensor([833,  44, 231, 263, 381, 457, 833,  44, 251, 302, 490, 833,  75, 205,
        308, 546, 833,  66, 247, 299, 457, 833,  71, 235, 299, 457, 833,  75,
        237, 299, 457, 833,  50, 214, 263, 457, 833,  66, 217, 302, 546, 833,
         71, 210, 308, 546, 833,  56, 225, 290, 485, 833,  50, 215, 266, 381,
        457, 833,  44, 240, 266, 457, 833,  70, 231, 263, 381, 457, 833,  50,
        249, 266, 457, 833,  55, 231, 323, 485, 833,  74, 210, 355, 546, 833,
         65, 202, 355, 546, 833,  70, 208, 355, 546, 833,  44, 256, 269, 457,
        833,  74, 243, 266, 457, 833,  43, 248, 326, 490, 833,  65, 223, 263,
        457, 833,  50, 206, 266, 381, 457, 833,  65, 213, 266, 457, 833,  70,
        211, 266], device='cuda:0')
tensor([ 44, 231, 263, 381, 457, 833,  44, 251, 302, 490, 833,  75, 205, 308,
        546, 833,  66, 247, 299, 457, 833,  71, 235, 299, 457, 833,  75, 237,
        299, 457, 833,  50, 214, 263, 457, 833,  66, 217, 302, 546, 833,  71,
        210, 308, 546, 833, 

In [20]:
import torch.nn.functional as F

softmaxed_tensor = F.softmax(output, dim=-1)
softmaxed_tensor.argmax(-1)

tensor([[ 34, 257, 357, 357, 357, 833, 256, 256, 357, 357, 833, 833,  54, 257,
         257, 357, 357, 833, 256, 257, 357, 357, 357, 833, 256, 257, 357, 357,
         357, 833, 256, 257, 357, 357, 357, 833, 257, 257, 357, 357, 357, 833,
         256, 257, 357, 357, 357, 833, 256, 257, 357, 357, 357, 833, 256, 257,
         357, 357, 357, 833, 256, 257, 357, 357, 833, 833,  54, 257, 257, 357,
         357, 833, 256, 257, 257, 357, 833, 833,  54, 257, 257, 357, 357, 833,
          50, 257, 257, 357, 357, 833,  54, 257, 257, 357, 357, 833,  34, 257,
         357, 357, 357, 833,  34, 257, 357, 357, 357, 833, 257, 256, 257, 357,
         357, 833, 257, 257, 257, 357, 357, 833, 256, 257, 357, 357, 357, 833,
         257, 257]], device='cuda:0')